serviceAccount: projects/pulsefm-484500/serviceAccounts/cloud-build-deployer@pulsefm-484500.iam.gserviceaccount.com

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: terraform
    dir: terraform
    entrypoint: /bin/bash
    env:
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=${_TERRAFORM_SA}
    args:
      - -c
      - |
        set -e
        apt-get update -qq && apt-get install -y -qq unzip
        curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o /tmp/terraform.zip
        unzip -o /tmp/terraform.zip -d /usr/local/bin/
        terraform init
        terraform apply -auto-approve \
          -var="project_id=${PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="artifact_repo=${_ARTIFACT_REPO}" \
          -var="cdn_hostname=${_CDN_HOSTNAME}" \
          -var="cdn_dns_zone_name=${_CDN_DNS_ZONE_NAME}" \
          -var="cdn_dns_name=${_CDN_DNS_NAME}" \
          -var="cdn_signed_cookie_key_name=${_CDN_SIGNING_KEY_NAME}" \
          -var="cdn_signed_cookie_key_value=${_CDN_SIGNING_KEY_VALUE}" \
          -var="nextjs_session_signing_key=${_NEXTJS_SESSION_SIGNING_KEY}" \
          -var="vote_api_image=${_VOTE_API_IMAGE}" \
          -var="encoder_image=${_ENCODER_IMAGE}" \
          -var="playback_service_image=${_PLAYBACK_SERVICE_IMAGE}" \
          -var="playback_stream_image=${_PLAYBACK_STREAM_IMAGE}" \
          -var="window_seconds=${_WINDOW_SECONDS}" \
          -var="options_per_window=${_OPTIONS_PER_WINDOW}" \
          -var="github_owner=${_GITHUB_OWNER}" \
          -var="github_repo=${_GITHUB_REPO}" \
          -var="github_branch=${_GITHUB_BRANCH}" \
          -var="modal_token_id=${_MODAL_TOKEN_ID}" \
          -var="modal_token_secret=${_MODAL_TOKEN_SECRET}"
  - name: gcr.io/cloud-builders/docker
    id: build-vote-api
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/vote-api:${SHORT_SHA}",
        "-f",
        "services/vote-api/Dockerfile",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    id: push-vote-api
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/vote-api:${SHORT_SHA}",
      ]
  - name: gcr.io/cloud-builders/docker
    id: build-encoder
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/encoder:${SHORT_SHA}",
        "-f",
        "services/encoder/Dockerfile",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    id: push-encoder
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/encoder:${SHORT_SHA}",
      ]
  - name: gcr.io/cloud-builders/docker
    id: build-playback-service
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-service:${SHORT_SHA}",
        "-f",
        "services/playback-service/Dockerfile",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    id: push-playback-service
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-service:${SHORT_SHA}",
      ]
  - name: gcr.io/cloud-builders/docker
    id: build-playback-stream
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-stream:${SHORT_SHA}",
        "-f",
        "services/playback-stream/Dockerfile",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    id: push-playback-stream
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-stream:${SHORT_SHA}",
      ]
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-services
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -e
        gcloud run deploy vote-api --region ${_REGION} --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/vote-api:${SHORT_SHA} --service-account vote-api@${PROJECT_ID}.iam.gserviceaccount.com --impersonate-service-account ${_TERRAFORM_SA}
        gcloud run deploy encoder --region ${_REGION} --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/encoder:${SHORT_SHA} --service-account encoder@${PROJECT_ID}.iam.gserviceaccount.com --impersonate-service-account ${_TERRAFORM_SA}
        gcloud run deploy playback-service --region ${_REGION} --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-service:${SHORT_SHA} --service-account playback-service@${PROJECT_ID}.iam.gserviceaccount.com --impersonate-service-account ${_TERRAFORM_SA}
        gcloud run deploy playback-stream --region ${_REGION} --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-stream:${SHORT_SHA} --service-account playback-stream@${PROJECT_ID}.iam.gserviceaccount.com --impersonate-service-account ${_TERRAFORM_SA}
substitutions:
  _REGION: northamerica-northeast1
  _ARTIFACT_REPO: pulsefm
  _CDN_HOSTNAME: "cdn.pulsefm.fm"
  _CDN_DNS_ZONE_NAME: "cdn-pulsefm-fm"
  _CDN_DNS_NAME: "cdn.pulsefm.fm."
  _CDN_SIGNING_KEY_NAME: "pulsefm-cdn-key"
  _CDN_SIGNING_KEY_VALUE: ""
  _NEXTJS_SESSION_SIGNING_KEY: ""
  _VOTE_API_IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/vote-api:placeholder"
  _ENCODER_IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/encoder:placeholder"
  _PLAYBACK_SERVICE_IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-service:placeholder"
  _PLAYBACK_STREAM_IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/playback-stream:placeholder"
  _WINDOW_SECONDS: "300"
  _OPTIONS_PER_WINDOW: "4"
  _GITHUB_OWNER: ""
  _GITHUB_REPO: ""
  _GITHUB_BRANCH: "main"
  _TERRAFORM_SA: ""
  _MODAL_TOKEN_ID: ""
  _MODAL_TOKEN_SECRET: ""

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
